version: "3"
services:
  rabbit-node-1:
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit-node-1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_USER:-admin}
  rabbit-node-2:
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit-node-2
    links:
      - rabbit-node-1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit-node-1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "15673:15672"
  rabbit-node-3:
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit-node-3
    links:
      - rabbit-node-1
      - rabbit-node-2
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit-node-1
    ports:
      - "5674:5672"
      - "15674:15672"
  rabbit-node-4:
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit-node-4
    links:
      - rabbit-node-1
      - rabbit-node-2
      - rabbit-node-3
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit-node-1
    ports:
      - "5675:5672"
      - "15675:15672"
  rabbit-node-5:
    image: lucifer8591/rabbitmq-server:3.7.17
    hostname: rabbit-node-5
    links:
      - rabbit-node-1
      - rabbit-node-2
      - rabbit-node-3
      - rabbit-node-4
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit-node-1
    ports:
      - "5676:5672"
      - "15676:15672"
